services:
  main_bot:
    build:
      context: .
    env_file:
     - env/main.env
    restart: on-failure
    depends_on:
      - postgres_main
    volumes:
     - ./bot:/bot

  postgres_main:
    image: postgres:16.2
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: timur.abdullin.2406@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - postgres_main

volumes:
  postgres_data:
  pgadmin: